In [2]:
import gym

In [4]:
env = gym.make('CartPole-v0')
for i_episode in range(20):
	observation=env.reset()
	for t in range(100):
		env.render()
		print(observation)
		action = env.action_space.sample()
		observation, reward, done, info  = env.step(action)
		if done:
			print("episode finished")
			break

[2017-06-20 19:40:33,441] Making new env: CartPole-v0


[ 0.04375053 -0.04161337  0.0196884  -0.0216639 ]
[ 0.04291826 -0.23701206  0.01925512  0.27716535]
[ 0.03817802 -0.04217003  0.02479843 -0.00938287]
[ 0.03733462  0.15258766  0.02461077 -0.29413959]
[ 0.04038638 -0.04287636  0.01872798  0.00620249]
[ 0.03952885  0.15197206  0.01885203 -0.28051319]
[ 0.04256829  0.34682009  0.01324176 -0.56719114]
[ 0.04950469  0.54175382  0.00189794 -0.85567312]
[ 0.06033977  0.73684985 -0.01521552 -1.14775866]
[ 0.07507676  0.93216712 -0.0381707  -1.44517383]
[ 0.09372011  1.12773737 -0.06707417 -1.74953498]
[ 0.11627485  1.32355387 -0.10206487 -2.06230427]
[ 0.14274593  1.12961008 -0.14331096 -1.80285755]
[ 0.16533813  0.93635095 -0.17936811 -1.55792998]
episode finished
[-0.0006329  -0.00685894  0.01721798  0.03237034]
[-0.00077008 -0.20222352  0.01786538  0.3304356 ]
[-0.00481455 -0.39759516  0.0244741   0.62869845]
[-0.01276646 -0.59304997  0.03704807  0.92898752]
[-0.02462746 -0.78865194  0.05562782  1.23307878]
[-0.04040049 -0.98444326  0.08028

In [3]:
import numpy as np

#hill climbing 
#initialize weight
#remember weights in the memory
def run_episode(env, parameters):
    observation = env.reset()
    totalreward = 0
    for _ in range(200):
        env.render()
        action = 0 if np.matmul(parameters, observation)<0 else 1
        observation, reward, done, info = env.step(action)
        totalreward += reward
        if done:
            break
    return totalreward
    
def train(submit):
    env = gym.make('CartPole-v0')
    episodes_per_uppdate = 5
    noise_scaling = 0.1
    parameters = np.random.rand(4)*2-1
    bestreward = 0
    
    for _ in range(2000):
        newparams = parameters + (np.random.rand(4)*2-1)*noise_scaling
        reward = run_episode(env, newparams)
        print("reward %d best %d"  % (reward, bestreward))
        if reward > bestreward: 
            bestreward = reward
            parameters = newparams
            if reward == 200:
                break

r = train(submit=False)
print(r)

[2017-06-20 19:44:08,437] Making new env: CartPole-v0


reward 9 best 0
reward 9 best 9
reward 8 best 9
reward 9 best 9
reward 10 best 9
reward 9 best 10
reward 8 best 10
reward 10 best 10
reward 8 best 10
reward 9 best 10
reward 9 best 10
reward 9 best 10
reward 9 best 10
reward 10 best 10
reward 8 best 10
reward 8 best 10
reward 9 best 10
reward 10 best 10
reward 9 best 10
reward 8 best 10
reward 8 best 10
reward 8 best 10
reward 9 best 10
reward 9 best 10
reward 9 best 10
reward 10 best 10
reward 9 best 10
reward 10 best 10
reward 8 best 10
reward 9 best 10
reward 9 best 10
reward 8 best 10
reward 9 best 10
reward 9 best 10
reward 9 best 10
reward 9 best 10
reward 9 best 10
reward 8 best 10
reward 8 best 10
reward 10 best 10
reward 8 best 10
reward 10 best 10
reward 8 best 10
reward 9 best 10
reward 9 best 10
reward 9 best 10
reward 9 best 10
reward 10 best 10
reward 9 best 10
reward 10 best 10
reward 9 best 10
reward 9 best 10
reward 8 best 10
reward 9 best 10
reward 9 best 10
reward 9 best 10
reward 9 best 10
reward 9 best 10
reward 10